Fix/update libs september
boomerang-io/flow.lib.streaming pull request #11
Opened 2022-09-12 14:21 UTC by AndreiOla

**Changed**
Updated plexus-utils lib, for fixing 2 MEDIUM vulnerabilities,

2022-09-12 14:25 UTC, AndreiOla commented
Hey @tlawrie ,
Please add me to Contributors for this lib, so I can add Reviewers and push into the main branch.
Also please add yourself as reviewer for this PR, as I am not allowed to do so.
I need this approved, so I can tag and use the new lib version to other services.

2022-09-20 12:50 UTC, AndreiOla commented
Hey @tlawrie  Please don't forget about this one.

2022-09-21 14:09 UTC, corcoja requested changes

2022-09-21 14:09 UTC, corcoja commented on pom.xml
> +	<version>0.4.1</version>
Increment version to `0.4.0` (after `0.4.0-rc.1`).

2022-09-22 16:07 UTC, corcoja approved these changes
LGTM! 👍🏻

2022-09-22 20:46 UTC, tlawrie approved these changes

2022-09-22 20:46 UTC, merged